var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/translator/translate/route.js")
R.c("server/chunks/[root-of-the-server]__1bmxs2q._.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/[root-of-the-server]__1l8rxcz._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__0cehawh._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_open-sse_0w5gft3._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/codex xoay_open-sse_0ohpik1._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_translator_translate_route_actions_0tdxkn_.js")
R.m(320860)
module.exports=R.m(320860).exports
