var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tunnel/tailscale-install/route.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__1jx3gb7._.js")
R.c("server/chunks/codex xoay_0nvcci6._.js")
R.c("server/chunks/codex xoay_src_lib_tunnel_index_0sg8iff.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_tunnel_tailscale-install_route_actions_0k-ky-n.js")
R.m(297476)
module.exports=R.m(297476).exports
