var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/[id]/models/route.js")
R.c("server/chunks/[root-of-the-server]__1ppf9pt._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__09fo_fv._.js")
R.c("server/chunks/[root-of-the-server]__0q2wfuq._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/1g8g_next_dist_esm_build_templates_app-route_0dgacln.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_providers_[id]_models_route_actions_1wkcbit.js")
R.m(612421)
module.exports=R.m(612421).exports
