var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/api/chat/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__0o8cjo3._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/codex xoay_1lqgfbe._.js")
R.c("server/chunks/[root-of-the-server]__1t6upid._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/codex xoay_open-sse_03x24fr._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/[root-of-the-server]__15cu5hp._.js")
R.c("server/chunks/codex xoay_open-sse_0ckyjsm._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/codex xoay_open-sse_0xhx0le._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_v1_api_chat_route_actions_19jcx5n.js")
R.m(821800)
module.exports=R.m(821800).exports
