var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/oauth/kiro/social-exchange/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__1r7zh04._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_open-sse_providers_0p3h_gj._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_oauth_kiro_social-exchange_route_actions_15wrn81.js")
R.m(956615)
module.exports=R.m(956615).exports
