var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/translator/send/route.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__11b6szd._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_open-sse_0xhx0le._.js")
R.c("server/chunks/codex xoay_open-sse_03x24fr._.js")
R.c("server/chunks/codex xoay_open-sse_0ckyjsm._.js")
R.c("server/chunks/[root-of-the-server]__15cu5hp._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_translator_send_route_actions_1rbj3no.js")
R.m(536612)
module.exports=R.m(536612).exports
