var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/oauth/[provider]/[action]/route.js")
R.c("server/chunks/[root-of-the-server]__0moryww._.js")
R.c("server/chunks/codex xoay_1wlqmjp._.js")
R.c("server/chunks/codex xoay_0no9oq5._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/codex xoay_src_lib_oauth_0rkhwv7._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/codex xoay_open-sse_03x24fr._.js")
R.c("server/chunks/codex xoay_open-sse_0ckyjsm._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/[root-of-the-server]__15cu5hp._.js")
R.c("server/chunks/codex xoay_open-sse_0xhx0le._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_oauth_[provider]_[action]_route_actions_01yjws7.js")
R.m(430860)
module.exports=R.m(430860).exports
