var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/dashboard/media-providers/web/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__089fnix._.js")
R.c("server/chunks/ssr/1g8g_1czznoz._.js")
R.c("server/chunks/ssr/1g8g_next_dist_esm_build_templates_app-page_1cf-u-t.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rxu-k4._.js")
R.c("server/chunks/ssr/1g8g_next_dist_0d3v6wq._.js")
R.c("server/chunks/ssr/codex xoay_1d67vrp._.js")
R.c("server/chunks/ssr/codex xoay_open-sse_0yl-rzi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__190j-q8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__034ddbw._.js")
R.c("server/chunks/ssr/1g8g_undici_0-0q_jh._.js")
R.c("server/chunks/ssr/codex xoay_1m95xgf._.js")
R.c("server/chunks/ssr/codex xoay_src_lib_db_index_1jd5c1p.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_0d9-rtb._.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_forbidden_0q-uwvo.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_unauthorized_0xp0i6d.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_global-error_0nzyu2_.js")
R.c("server/chunks/ssr/codex xoay_src_shared_components_Loading_1ktysz-.js")
R.c("server/chunks/ssr/codex xoay_src_0l1scyo._.js")
R.c("server/chunks/ssr/0k2i_server_app_(dashboard)_dashboard_media-providers_web_page_actions_0potbky.js")
R.m(991448)
module.exports=R.m(991448).exports
