var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/route.js")
R.c("server/chunks/[root-of-the-server]__0gr7l1c._.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/1g8g_bcryptjs_index_0ze_p7u.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_open-sse_0154wx-._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_settings_route_actions_0n_688v.js")
R.m(335835)
module.exports=R.m(335835).exports
