var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tunnel/tailscale-check/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/[root-of-the-server]__15ja9ym._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_0nvcci6._.js")
R.c("server/chunks/codex xoay_src_lib_tunnel_index_0sg8iff.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_tunnel_tailscale-check_route_actions_08lef3s.js")
R.m(881591)
module.exports=R.m(881591).exports
