var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yt5nwy._.js")
R.c("server/chunks/ssr/1g8g_1czznoz._.js")
R.c("server/chunks/ssr/1g8g_next_dist_esm_build_templates_app-page_136hck_.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rxu-k4._.js")
R.c("server/chunks/ssr/1g8g_next_dist_0d3v6wq._.js")
R.c("server/chunks/ssr/codex xoay_1d67vrp._.js")
R.c("server/chunks/ssr/codex xoay_open-sse_0yl-rzi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__190j-q8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__034ddbw._.js")
R.c("server/chunks/ssr/1g8g_undici_0-0q_jh._.js")
R.c("server/chunks/ssr/codex xoay_1m95xgf._.js")
R.c("server/chunks/ssr/codex xoay_src_lib_db_index_1jd5c1p.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_0d9-rtb._.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_forbidden_0q-uwvo.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_unauthorized_0xp0i6d.js")
R.c("server/chunks/ssr/1g8g_next_dist_client_components_builtin_global-error_0nzyu2_.js")
R.c("server/chunks/ssr/codex xoay__next-internal_server_app_login_page_actions_0wbj_2p.js")
R.m(891419)
module.exports=R.m(891419).exports
