var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/oauth/kiro/api-key/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__037jr4q._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_open-sse_providers_0p3h_gj._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_oauth_kiro_api-key_route_actions_13twg_r.js")
R.m(837480)
module.exports=R.m(837480).exports
