var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/models/test/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0dypge_._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_models_test_route_actions_0eeuiqr.js")
R.m(329536)
module.exports=R.m(329536).exports
