var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/providers/test-batch/route.js")
R.c("server/chunks/[root-of-the-server]__12t93_m._.js")
R.c("server/chunks/codex xoay_src_app_api_providers_[id]_test_testUtils_13fj3h1.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/[root-of-the-server]__0pvsq50._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/[root-of-the-server]__1h9r0t3._.js")
R.c("server/chunks/1dm7__next-internal_server_app_api_providers_test-batch_route_actions_062e0hj.js")
R.m(176740)
module.exports=R.m(176740).exports
