var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/media-providers/tts/elevenlabs/voices/route.js")
R.c("server/chunks/codex xoay_open-sse_handlers_ttsCore_0l5-1rd.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/[root-of-the-server]__1a6wyz9._.js")
R.c("server/chunks/0k2i_server_app_api_media-providers_tts_elevenlabs_voices_route_actions_0h56237.js")
R.m(903200)
module.exports=R.m(903200).exports
