var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/oidc/test/route.js")
R.c("server/chunks/[root-of-the-server]__1sv8655._.js")
R.c("server/chunks/codex xoay_012wwtj._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1g8g_jose_dist_webapi_01800ky._.js")
R.c("server/chunks/1g8g_next_0_38jwt._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_auth_oidc_test_route_actions_1to0fbn.js")
R.m(330475)
module.exports=R.m(330475).exports
