var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/web/fetch/route.js")
R.c("server/chunks/[root-of-the-server]__04ow22c._.js")
R.c("server/chunks/codex xoay_1ihlj26._.js")
R.c("server/chunks/[root-of-the-server]__1ppf9pt._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/[root-of-the-server]__19eg6y3._.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/codex xoay_1lqgfbe._.js")
R.c("server/chunks/1g8g_next_dist_esm_build_templates_app-route_1r9ob3z.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_v1_web_fetch_route_actions_1nzh119.js")
R.m(675631)
module.exports=R.m(675631).exports
