var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tunnel/status/route.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_src_lib_tunnel_index_0sg8iff.js")
R.c("server/chunks/[root-of-the-server]__1-6jvys._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_0nvcci6._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_tunnel_status_route_actions_0rdmbf5.js")
R.m(280983)
module.exports=R.m(280983).exports
