var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/telegram/webhook/route.js")
R.c("server/chunks/[root-of-the-server]__0xd60y5._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_src_lib_supabase_1uxn4w5.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_telegram_webhook_route_actions_0fadyuw.js")
R.m(169542)
module.exports=R.m(169542).exports
