var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/embeddings/route.js")
R.c("server/chunks/[root-of-the-server]__0blxuj0._.js")
R.c("server/chunks/codex xoay_0lpmg81._.js")
R.c("server/chunks/[root-of-the-server]__0hnz799._.js")
R.c("server/chunks/codex xoay_open-sse_19meq3u._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/codex xoay_00lgxs_._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/codex xoay_open-sse_04dqu0k._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1ei4vkh._.js")
R.c("server/chunks/1g8g_undici_0va01ks._.js")
R.c("server/chunks/[root-of-the-server]__15cu5hp._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/codex xoay_open-sse_0ohpik1._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_v1_embeddings_route_actions_05_vk2f.js")
R.m(916464)
module.exports=R.m(916464).exports
