var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/database/route.js")
R.c("server/chunks/[root-of-the-server]__1dbcke7._.js")
R.c("server/chunks/1g8g_bcryptjs_index_0ze_p7u.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_settings_database_route_actions_1yj5p76.js")
R.m(727779)
module.exports=R.m(727779).exports
