var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/cli-tools/antigravity-mitm/alias/route.js")
R.c("server/chunks/[root-of-the-server]__0muy048._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0mmpwj2._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_0nvcci6._.js")
R.c("server/chunks/0k2i_server_app_api_cli-tools_antigravity-mitm_alias_route_actions_1u0l36k.js")
R.m(857738)
module.exports=R.m(857738).exports
