var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/combos/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__1xl1d8y._.js")
R.c("server/chunks/codex xoay_open-sse_providers_1zn2bjh._.js")
R.c("server/chunks/[root-of-the-server]__1zqkb6m._.js")
R.c("server/chunks/1g8g_next_1xmxjye._.js")
R.c("server/chunks/codex xoay_src_lib_db_12ns7lj._.js")
R.c("server/chunks/[root-of-the-server]__0_kkss-._.js")
R.c("server/chunks/codex xoay_open-sse_0154wx-._.js")
R.c("server/chunks/codex xoay__next-internal_server_app_api_combos_[id]_route_actions_0ky2vl4.js")
R.m(515587)
module.exports=R.m(515587).exports
